const event =  {
    "_id": "5d4f8597736a117fe680b83c",
    "title": "The Hav Mercy show",
    "description": "Going to be soooo much fun. Endless suya and goat and beautiful people celebrating amazing culture.\n\nFeaturing a live band and music by Seagraves. See you all soon!",
    "endDate": "2019-10-02",
    "startDate": "2019-10-02",
    "eventType": "17",
    "image": {
      "cdnUri": "https://res.cloudinary.com/dzsf703vh/image/upload/v1564787834/zrtj1pjky7lnzta1h1l6.jpg",
      "files": [
        ""
      ]
    },
    "location": {
      "name": "Cloak & Dagger, U Street Northwest, Washington, DC, USA",
      "address": {
        "streetAddress": "1359 U St NW",
        "city": "Washington",
        "state": "DC",
        "postalCode": "20009",
        "country": "US"
      }
    },
    "organizer": "Freshly Breemed",
    "refundable": true,
    "tags": "",
    "ticketTypes": {
      "GA": {
        "name": "GA",
        "type": "paid",
        "price": 15,
        "fees": 2.45,
        "currentQuantity": 10,
        "startingQuantity": 20
      },
      "RSVP": {
        "name": "RSVP",
        "type": "rsvp",
        "price": 0,
        "fees": 0,
        "startingQuantity": 20,
        "currentQuantity": 2
      }
    },
    "user": "",
    "doorTime": "",
    "eventStatus": "live",
    "organizerId": "google-oauth2|113156531283332339776",
    "tickets": [
      {
        "id": "ch_1FFApeGNRUDqyjL3zFpFWwFR",
        "object": "charge",
        "amount": 1745,
        "amount_refunded": 0,
        "application": null,
        "application_fee": null,
        "application_fee_amount": null,
        "balance_transaction": "txn_1FFApeGNRUDqyjL3kuRBJnkO",
        "billing_details": {
          "address": {
            "city": "Silver Spring",
            "country": "United States",
            "line1": "14238 Castle Blvd",
            "line2": null,
            "postal_code": "20904",
            "state": "MD"
          },
          "email": null,
          "name": "ebrima Solomon jobe",
          "phone": null
        },
        "captured": true,
        "created": 1567650982,
        "currency": "usd",
        "customer": null,
        "description": null,
        "destination": null,
        "dispute": null,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {},
        "invoice": null,
        "livemode": false,
        "metadata": {
          "eventId": "5d4f8597736a117fe680b83c",
          "updatedAt": "1567647519",
          "GA": "1",
          "RSVP": "2"
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "risk_level": "normal",
          "risk_score": 62,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "payment_intent": null,
        "payment_method": "card_1FFApaGNRUDqyjL36Zryq1eW",
        "payment_method_details": {
          "card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": "pass",
              "address_postal_code_check": "pass",
              "cvc_check": "pass"
            },
            "country": "US",
            "exp_month": 2,
            "exp_year": 2032,
            "fingerprint": "xvoovnnTKuci9zAA",
            "funding": "credit",
            "last4": "4242",
            "three_d_secure": null,
            "wallet": null
          },
          "type": "card"
        },
        "receipt_email": null,
        "receipt_number": null,
        "receipt_url": "https://pay.stripe.com/receipts/acct_1EWUgYGNRUDqyjL3/ch_1FFApeGNRUDqyjL3zFpFWwFR/rcpt_FkgCxf9JDjjwCeUfD22tYaUEne513uX",
        "refunded": false,
        "refunds": {
          "object": "list",
          "data": [],
          "has_more": false,
          "total_count": 0,
          "url": "/v1/charges/ch_1FFApeGNRUDqyjL3zFpFWwFR/refunds"
        },
        "review": null,
        "shipping": null,
        "source": {
          "id": "card_1FFApaGNRUDqyjL36Zryq1eW",
          "object": "card",
          "address_city": "Silver Spring",
          "address_country": "United States",
          "address_line1": "14238 Castle Blvd",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "MD",
          "address_zip": "20904",
          "address_zip_check": "pass",
          "brand": "Visa",
          "country": "US",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 2,
          "exp_year": 2032,
          "fingerprint": "xvoovnnTKuci9zAA",
          "funding": "credit",
          "last4": "4242",
          "metadata": {},
          "name": "ebrima Solomon jobe",
          "tokenization_method": null
        },
        "source_transfer": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "succeeded",
        "transfer_data": null,
        "transfer_group": null
      },
      {
        "id": "ch_1FFApeGNRUDqyjL3zFpFWwFR",
        "object": "charge",
        "amount": 1745,
        "amount_refunded": 0,
        "application": null,
        "application_fee": null,
        "application_fee_amount": null,
        "balance_transaction": "txn_1FFApeGNRUDqyjL3kuRBJnkO",
        "billing_details": {
          "address": {
            "city": "Silver Spring",
            "country": "United States",
            "line1": "14238 Castle Blvd",
            "line2": null,
            "postal_code": "20904",
            "state": "MD"
          },
          "email": null,
          "name": "ebrima Solomon jobe",
          "phone": null
        },
        "captured": true,
        "created": 1567650982,
        "currency": "usd",
        "customer": null,
        "description": null,
        "destination": null,
        "dispute": null,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {},
        "invoice": null,
        "livemode": false,
        "metadata": {
          "eventId": "5d4f8597736a117fe680b83c",
          "updatedAt": "1567647519",
          "GA": "1",
          "RSVP": "2"
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "risk_level": "normal",
          "risk_score": 62,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "payment_intent": null,
        "payment_method": "card_1FFApaGNRUDqyjL36Zryq1eW",
        "payment_method_details": {
          "card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": "pass",
              "address_postal_code_check": "pass",
              "cvc_check": "pass"
            },
            "country": "US",
            "exp_month": 2,
            "exp_year": 2032,
            "fingerprint": "xvoovnnTKuci9zAA",
            "funding": "credit",
            "last4": "4242",
            "three_d_secure": null,
            "wallet": null
          },
          "type": "card"
        },
        "receipt_email": null,
        "receipt_number": null,
        "receipt_url": "https://pay.stripe.com/receipts/acct_1EWUgYGNRUDqyjL3/ch_1FFApeGNRUDqyjL3zFpFWwFR/rcpt_FkgCxf9JDjjwCeUfD22tYaUEne513uX",
        "refunded": false,
        "refunds": {
          "object": "list",
          "data": [],
          "has_more": false,
          "total_count": 0,
          "url": "/v1/charges/ch_1FFApeGNRUDqyjL3zFpFWwFR/refunds"
        },
        "review": null,
        "shipping": null,
        "source": {
          "id": "card_1FFApaGNRUDqyjL36Zryq1eW",
          "object": "card",
          "address_city": "Silver Spring",
          "address_country": "United States",
          "address_line1": "14238 Castle Blvd",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "MD",
          "address_zip": "20904",
          "address_zip_check": "pass",
          "brand": "Visa",
          "country": "US",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 2,
          "exp_year": 2032,
          "fingerprint": "xvoovnnTKuci9zAA",
          "funding": "credit",
          "last4": "4242",
          "metadata": {},
          "name": "ebrima Solomon jobe",
          "tokenization_method": null
        },
        "source_transfer": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "succeeded",
        "transfer_data": null,
        "transfer_group": null
      },
      {
        "id": "ch_1FF9vnGNRUDqyjL39ftzKeff",
        "object": "charge",
        "amount": 1745,
        "amount_refunded": 0,
        "application": null,
        "application_fee": null,
        "application_fee_amount": null,
        "balance_transaction": "txn_1FF9vnGNRUDqyjL3nC4SNyvw",
        "billing_details": {
          "address": {
            "city": "Silver Spring",
            "country": "United States",
            "line1": "14238 Castle Blvd",
            "line2": null,
            "postal_code": "20904",
            "state": "MD"
          },
          "email": null,
          "name": "Ant123",
          "phone": null
        },
        "captured": true,
        "created": 1567647519,
        "currency": "usd",
        "customer": null,
        "description": null,
        "destination": null,
        "dispute": null,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {},
        "invoice": null,
        "livemode": false,
        "metadata": {
          "eventId": "5d4f8597736a117fe680b83c",
          "updatedAt": "1567624041",
          "GA": "1",
          "RSVP": "0"
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "risk_level": "normal",
          "risk_score": 31,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "payment_intent": null,
        "payment_method": "card_1FF9vkGNRUDqyjL3c2uk8oaS",
        "payment_method_details": {
          "card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": "pass",
              "address_postal_code_check": "pass",
              "cvc_check": "pass"
            },
            "country": "US",
            "exp_month": 2,
            "exp_year": 2032,
            "fingerprint": "xvoovnnTKuci9zAA",
            "funding": "credit",
            "last4": "4242",
            "three_d_secure": null,
            "wallet": null
          },
          "type": "card"
        },
        "receipt_email": null,
        "receipt_number": null,
        "receipt_url": "https://pay.stripe.com/receipts/acct_1EWUgYGNRUDqyjL3/ch_1FF9vnGNRUDqyjL39ftzKeff/rcpt_FkfGTfsIbM6TlgIqu18WZW164Gc9cZx",
        "refunded": false,
        "refunds": {
          "object": "list",
          "data": [],
          "has_more": false,
          "total_count": 0,
          "url": "/v1/charges/ch_1FF9vnGNRUDqyjL39ftzKeff/refunds"
        },
        "review": null,
        "shipping": null,
        "source": {
          "id": "card_1FF9vkGNRUDqyjL3c2uk8oaS",
          "object": "card",
          "address_city": "Silver Spring",
          "address_country": "United States",
          "address_line1": "14238 Castle Blvd",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "MD",
          "address_zip": "20904",
          "address_zip_check": "pass",
          "brand": "Visa",
          "country": "US",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 2,
          "exp_year": 2032,
          "fingerprint": "xvoovnnTKuci9zAA",
          "funding": "credit",
          "last4": "4242",
          "metadata": {},
          "name": "Ant123",
          "tokenization_method": null
        },
        "source_transfer": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "succeeded",
        "transfer_data": null,
        "transfer_group": null
      },
      {
        "id": "ch_1FEQLNGNRUDqyjL3X5cgOyf8",
        "object": "charge",
        "amount": 3490,
        "amount_refunded": 0,
        "application": null,
        "application_fee": null,
        "application_fee_amount": null,
        "balance_transaction": "txn_1FEQLOGNRUDqyjL3106TTrvB",
        "billing_details": {
          "address": {
            "city": "silver spring",
            "country": "United States",
            "line1": "3751 Castle terrace",
            "line2": null,
            "postal_code": "20904",
            "state": "MD"
          },
          "email": null,
          "name": "Fred Seagraves",
          "phone": null
        },
        "captured": true,
        "created": 1567472281,
        "currency": "usd",
        "customer": null,
        "description": null,
        "destination": null,
        "dispute": null,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {},
        "invoice": null,
        "livemode": false,
        "metadata": {
          "eventId": "5d4f8597736a117fe680b83c",
          "GA": "2",
          "RSVP": "0"
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "risk_level": "normal",
          "risk_score": 42,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "payment_intent": null,
        "payment_method": "card_1FEQLKGNRUDqyjL3JpuOOQbJ",
        "payment_method_details": {
          "card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": "pass",
              "address_postal_code_check": "pass",
              "cvc_check": "pass"
            },
            "country": "US",
            "exp_month": 2,
            "exp_year": 2032,
            "fingerprint": "xvoovnnTKuci9zAA",
            "funding": "credit",
            "last4": "4242",
            "three_d_secure": null,
            "wallet": null
          },
          "type": "card"
        },
        "receipt_email": null,
        "receipt_number": null,
        "receipt_url": "https://pay.stripe.com/receipts/acct_1EWUgYGNRUDqyjL3/ch_1FEQLNGNRUDqyjL3X5cgOyf8/rcpt_Fju91nxrsldCNksode8OT179jkOpkig",
        "refunded": false,
        "refunds": {
          "object": "list",
          "data": [],
          "has_more": false,
          "total_count": 0,
          "url": "/v1/charges/ch_1FEQLNGNRUDqyjL3X5cgOyf8/refunds"
        },
        "review": null,
        "shipping": null,
        "source": {
          "id": "card_1FEQLKGNRUDqyjL3JpuOOQbJ",
          "object": "card",
          "address_city": "silver spring",
          "address_country": "United States",
          "address_line1": "3751 Castle terrace",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "MD",
          "address_zip": "20904",
          "address_zip_check": "pass",
          "brand": "Visa",
          "country": "US",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 2,
          "exp_year": 2032,
          "fingerprint": "xvoovnnTKuci9zAA",
          "funding": "credit",
          "last4": "4242",
          "metadata": {},
          "name": "Fred Seagraves",
          "tokenization_method": null
        },
        "source_transfer": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "succeeded",
        "transfer_data": null,
        "transfer_group": null
      },
      {
        "id": "ch_1FEQMOGNRUDqyjL3cv72hX9S",
        "object": "charge",
        "amount": 1745,
        "amount_refunded": 0,
        "application": null,
        "application_fee": null,
        "application_fee_amount": null,
        "balance_transaction": "txn_1FEQMPGNRUDqyjL38aCr0209",
        "billing_details": {
          "address": {
            "city": "Silver Spring",
            "country": "United States",
            "line1": "14238 Castle Blvd",
            "line2": null,
            "postal_code": "20904",
            "state": "MD"
          },
          "email": null,
          "name": "ebrima Solomon jobe",
          "phone": null
        },
        "captured": true,
        "created": 1567472344,
        "currency": "usd",
        "customer": null,
        "description": null,
        "destination": null,
        "dispute": null,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {},
        "invoice": null,
        "livemode": false,
        "metadata": {
          "eventId": "5d4f8597736a117fe680b83c",
          "GA": "1",
          "RSVP": "0"
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "risk_level": "normal",
          "risk_score": 30,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "payment_intent": null,
        "payment_method": "card_1FEQMLGNRUDqyjL3iKH4G5Ff",
        "payment_method_details": {
          "card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": "pass",
              "address_postal_code_check": "pass",
              "cvc_check": "pass"
            },
            "country": "US",
            "exp_month": 2,
            "exp_year": 2032,
            "fingerprint": "xvoovnnTKuci9zAA",
            "funding": "credit",
            "last4": "4242",
            "three_d_secure": null,
            "wallet": null
          },
          "type": "card"
        },
        "receipt_email": null,
        "receipt_number": null,
        "receipt_url": "https://pay.stripe.com/receipts/acct_1EWUgYGNRUDqyjL3/ch_1FEQMOGNRUDqyjL3cv72hX9S/rcpt_FjuAPwxvVfe8E1rbCXWWU4uFP2Rj0d5",
        "refunded": false,
        "refunds": {
          "object": "list",
          "data": [],
          "has_more": false,
          "total_count": 0,
          "url": "/v1/charges/ch_1FEQMOGNRUDqyjL3cv72hX9S/refunds"
        },
        "review": null,
        "shipping": null,
        "source": {
          "id": "card_1FEQMLGNRUDqyjL3iKH4G5Ff",
          "object": "card",
          "address_city": "Silver Spring",
          "address_country": "United States",
          "address_line1": "14238 Castle Blvd",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "MD",
          "address_zip": "20904",
          "address_zip_check": "pass",
          "brand": "Visa",
          "country": "US",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 2,
          "exp_year": 2032,
          "fingerprint": "xvoovnnTKuci9zAA",
          "funding": "credit",
          "last4": "4242",
          "metadata": {},
          "name": "ebrima Solomon jobe",
          "tokenization_method": null
        },
        "source_transfer": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "succeeded",
        "transfer_data": null,
        "transfer_group": null
      },
      {
        "id": "ch_1FEQMQGNRUDqyjL3POLi6O5I",
        "object": "charge",
        "amount": 3490,
        "amount_refunded": 0,
        "application": null,
        "application_fee": null,
        "application_fee_amount": null,
        "balance_transaction": "txn_1FEQMQGNRUDqyjL3CRzOWAKB",
        "billing_details": {
          "address": {
            "city": "Los Angeles",
            "country": "United States",
            "line1": "1762 West blvd",
            "line2": null,
            "postal_code": "90019",
            "state": "CA"
          },
          "email": null,
          "name": "Ebrima Jobe",
          "phone": null
        },
        "captured": true,
        "created": 1567472346,
        "currency": "usd",
        "customer": null,
        "description": null,
        "destination": null,
        "dispute": null,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {},
        "invoice": null,
        "livemode": false,
        "metadata": {
          "eventId": "5d4f8597736a117fe680b83c",
          "GA": "2",
          "RSVP": "0"
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "risk_level": "normal",
          "risk_score": 20,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "payment_intent": null,
        "payment_method": "card_1FEQMMGNRUDqyjL3WIhROnoU",
        "payment_method_details": {
          "card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": "pass",
              "address_postal_code_check": "pass",
              "cvc_check": "pass"
            },
            "country": "US",
            "exp_month": 12,
            "exp_year": 2032,
            "fingerprint": "xvoovnnTKuci9zAA",
            "funding": "credit",
            "last4": "4242",
            "three_d_secure": null,
            "wallet": null
          },
          "type": "card"
        },
        "receipt_email": null,
        "receipt_number": null,
        "receipt_url": "https://pay.stripe.com/receipts/acct_1EWUgYGNRUDqyjL3/ch_1FEQMQGNRUDqyjL3POLi6O5I/rcpt_FjuAdVCsSsxANItXDhejaRRrVvljoKd",
        "refunded": false,
        "refunds": {
          "object": "list",
          "data": [],
          "has_more": false,
          "total_count": 0,
          "url": "/v1/charges/ch_1FEQMQGNRUDqyjL3POLi6O5I/refunds"
        },
        "review": null,
        "shipping": null,
        "source": {
          "id": "card_1FEQMMGNRUDqyjL3WIhROnoU",
          "object": "card",
          "address_city": "Los Angeles",
          "address_country": "United States",
          "address_line1": "1762 West blvd",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "CA",
          "address_zip": "90019",
          "address_zip_check": "pass",
          "brand": "Visa",
          "country": "US",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 12,
          "exp_year": 2032,
          "fingerprint": "xvoovnnTKuci9zAA",
          "funding": "credit",
          "last4": "4242",
          "metadata": {},
          "name": "Ebrima Jobe",
          "tokenization_method": null
        },
        "source_transfer": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "succeeded",
        "transfer_data": null,
        "transfer_group": null
      },
      {
        "id": "ch_1FER80GNRUDqyjL3aAeRv802",
        "object": "charge",
        "amount": 1745,
        "amount_refunded": 0,
        "application": null,
        "application_fee": null,
        "application_fee_amount": null,
        "balance_transaction": "txn_1FER80GNRUDqyjL3VYKke5eC",
        "billing_details": {
          "address": {
            "city": "Los angeles",
            "country": "United States",
            "line1": "1762 west blvd",
            "line2": null,
            "postal_code": "90019",
            "state": "CA"
          },
          "email": null,
          "name": "ebrima s jobe",
          "phone": null
        },
        "captured": true,
        "created": 1567475296,
        "currency": "usd",
        "customer": null,
        "description": null,
        "destination": null,
        "dispute": null,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {},
        "invoice": null,
        "livemode": false,
        "metadata": {
          "eventId": "5d4f8597736a117fe680b83c",
          "updatedAt": "1567472346",
          "GA": "1",
          "RSVP": "0"
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "risk_level": "normal",
          "risk_score": 16,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "payment_intent": null,
        "payment_method": "card_1FER7xGNRUDqyjL3ox7JWshG",
        "payment_method_details": {
          "card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": "pass",
              "address_postal_code_check": "pass",
              "cvc_check": "pass"
            },
            "country": "US",
            "exp_month": 5,
            "exp_year": 2055,
            "fingerprint": "xvoovnnTKuci9zAA",
            "funding": "credit",
            "last4": "4242",
            "three_d_secure": null,
            "wallet": null
          },
          "type": "card"
        },
        "receipt_email": null,
        "receipt_number": null,
        "receipt_url": "https://pay.stripe.com/receipts/acct_1EWUgYGNRUDqyjL3/ch_1FER80GNRUDqyjL3aAeRv802/rcpt_FjuxFLZLE3m7O1ggdUffRJoASztDplB",
        "refunded": false,
        "refunds": {
          "object": "list",
          "data": [],
          "has_more": false,
          "total_count": 0,
          "url": "/v1/charges/ch_1FER80GNRUDqyjL3aAeRv802/refunds"
        },
        "review": null,
        "shipping": null,
        "source": {
          "id": "card_1FER7xGNRUDqyjL3ox7JWshG",
          "object": "card",
          "address_city": "Los angeles",
          "address_country": "United States",
          "address_line1": "1762 west blvd",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "CA",
          "address_zip": "90019",
          "address_zip_check": "pass",
          "brand": "Visa",
          "country": "US",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 5,
          "exp_year": 2055,
          "fingerprint": "xvoovnnTKuci9zAA",
          "funding": "credit",
          "last4": "4242",
          "metadata": {},
          "name": "ebrima s jobe",
          "tokenization_method": null
        },
        "source_transfer": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "succeeded",
        "transfer_data": null,
        "transfer_group": null
      },
      {
        "id": "ch_1FERCmGNRUDqyjL3K3pZQ9v0",
        "object": "charge",
        "amount": 1745,
        "amount_refunded": 0,
        "application": null,
        "application_fee": null,
        "application_fee_amount": null,
        "balance_transaction": "txn_1FERCmGNRUDqyjL3V1eKh2Yv",
        "billing_details": {
          "address": {
            "city": "silver spring",
            "country": "United States",
            "line1": "3751 Castle terrace",
            "line2": null,
            "postal_code": "20904",
            "state": "MD"
          },
          "email": null,
          "name": "Fred Seagraves",
          "phone": null
        },
        "captured": true,
        "created": 1567475592,
        "currency": "usd",
        "customer": null,
        "description": null,
        "destination": null,
        "dispute": null,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {},
        "invoice": null,
        "livemode": false,
        "metadata": {
          "eventId": "5d4f8597736a117fe680b83c",
          "updatedAt": "1567475296",
          "GA": "1",
          "RSVP": "0"
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "risk_level": "normal",
          "risk_score": 17,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "payment_intent": null,
        "payment_method": "card_1FERCjGNRUDqyjL3y3AHGpvL",
        "payment_method_details": {
          "card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": "pass",
              "address_postal_code_check": "pass",
              "cvc_check": "pass"
            },
            "country": "US",
            "exp_month": 3,
            "exp_year": 2055,
            "fingerprint": "xvoovnnTKuci9zAA",
            "funding": "credit",
            "last4": "4242",
            "three_d_secure": null,
            "wallet": null
          },
          "type": "card"
        },
        "receipt_email": null,
        "receipt_number": null,
        "receipt_url": "https://pay.stripe.com/receipts/acct_1EWUgYGNRUDqyjL3/ch_1FERCmGNRUDqyjL3K3pZQ9v0/rcpt_Fjv2iVjHjIPwrl6YfyvaHHhoFYvvZIW",
        "refunded": false,
        "refunds": {
          "object": "list",
          "data": [],
          "has_more": false,
          "total_count": 0,
          "url": "/v1/charges/ch_1FERCmGNRUDqyjL3K3pZQ9v0/refunds"
        },
        "review": null,
        "shipping": null,
        "source": {
          "id": "card_1FERCjGNRUDqyjL3y3AHGpvL",
          "object": "card",
          "address_city": "silver spring",
          "address_country": "United States",
          "address_line1": "3751 Castle terrace",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "MD",
          "address_zip": "20904",
          "address_zip_check": "pass",
          "brand": "Visa",
          "country": "US",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 3,
          "exp_year": 2055,
          "fingerprint": "xvoovnnTKuci9zAA",
          "funding": "credit",
          "last4": "4242",
          "metadata": {},
          "name": "Fred Seagraves",
          "tokenization_method": null
        },
        "source_transfer": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "succeeded",
        "transfer_data": null,
        "transfer_group": null
      },
      {
        "id": "ch_1FERxvGNRUDqyjL3YQNUR8w0",
        "object": "charge",
        "amount": 1745,
        "amount_refunded": 0,
        "application": null,
        "application_fee": null,
        "application_fee_amount": null,
        "balance_transaction": "txn_1FERxvGNRUDqyjL3hqUMiKKR",
        "billing_details": {
          "address": {
            "city": "SIlver Spring",
            "country": "United States",
            "line1": "9617 Cotrell Terrace",
            "line2": null,
            "postal_code": "20904",
            "state": "MD"
          },
          "email": null,
          "name": "Carl L Garner Jr",
          "phone": null
        },
        "captured": true,
        "created": 1567478515,
        "currency": "usd",
        "customer": null,
        "description": null,
        "destination": null,
        "dispute": null,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {},
        "invoice": null,
        "livemode": false,
        "metadata": {
          "eventId": "5d4f8597736a117fe680b83c",
          "updatedAt": "1567475592",
          "GA": "1",
          "RSVP": "0"
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "risk_level": "normal",
          "risk_score": 36,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "payment_intent": null,
        "payment_method": "card_1FERxsGNRUDqyjL3KJ90ydFv",
        "payment_method_details": {
          "card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": "pass",
              "address_postal_code_check": "pass",
              "cvc_check": "pass"
            },
            "country": "US",
            "exp_month": 3,
            "exp_year": 2055,
            "fingerprint": "xvoovnnTKuci9zAA",
            "funding": "credit",
            "last4": "4242",
            "three_d_secure": null,
            "wallet": null
          },
          "type": "card"
        },
        "receipt_email": null,
        "receipt_number": null,
        "receipt_url": "https://pay.stripe.com/receipts/acct_1EWUgYGNRUDqyjL3/ch_1FERxvGNRUDqyjL3YQNUR8w0/rcpt_FjvpYpf4BOQ9mFSwscRCbfbI6sQ62y1",
        "refunded": false,
        "refunds": {
          "object": "list",
          "data": [],
          "has_more": false,
          "total_count": 0,
          "url": "/v1/charges/ch_1FERxvGNRUDqyjL3YQNUR8w0/refunds"
        },
        "review": null,
        "shipping": null,
        "source": {
          "id": "card_1FERxsGNRUDqyjL3KJ90ydFv",
          "object": "card",
          "address_city": "SIlver Spring",
          "address_country": "United States",
          "address_line1": "9617 Cotrell Terrace",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "MD",
          "address_zip": "20904",
          "address_zip_check": "pass",
          "brand": "Visa",
          "country": "US",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 3,
          "exp_year": 2055,
          "fingerprint": "xvoovnnTKuci9zAA",
          "funding": "credit",
          "last4": "4242",
          "metadata": {},
          "name": "Carl L Garner Jr",
          "tokenization_method": null
        },
        "source_transfer": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "succeeded",
        "transfer_data": null,
        "transfer_group": null
      },
      {
        "id": "ch_1FEVHiGNRUDqyjL3acxVIi80",
        "object": "charge",
        "amount": 1745,
        "amount_refunded": 0,
        "application": null,
        "application_fee": null,
        "application_fee_amount": null,
        "balance_transaction": "txn_1FEVHiGNRUDqyjL3MkcmlZrA",
        "billing_details": {
          "address": {
            "city": "Silver Spring",
            "country": "United States",
            "line1": "14238 Castle Blvd",
            "line2": null,
            "postal_code": "20904",
            "state": "MD"
          },
          "email": null,
          "name": "ebrima Solomon jobe",
          "phone": null
        },
        "captured": true,
        "created": 1567491274,
        "currency": "usd",
        "customer": null,
        "description": null,
        "destination": null,
        "dispute": null,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {},
        "invoice": null,
        "livemode": false,
        "metadata": {
          "eventId": "5d4f8597736a117fe680b83c",
          "updatedAt": "1567478516",
          "GA": "1",
          "RSVP": "0"
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "risk_level": "normal",
          "risk_score": 51,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "payment_intent": null,
        "payment_method": "card_1FEVHfGNRUDqyjL3rwrdtE1E",
        "payment_method_details": {
          "card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": "pass",
              "address_postal_code_check": "pass",
              "cvc_check": "pass"
            },
            "country": "US",
            "exp_month": 2,
            "exp_year": 2032,
            "fingerprint": "xvoovnnTKuci9zAA",
            "funding": "credit",
            "last4": "4242",
            "three_d_secure": null,
            "wallet": null
          },
          "type": "card"
        },
        "receipt_email": null,
        "receipt_number": null,
        "receipt_url": "https://pay.stripe.com/receipts/acct_1EWUgYGNRUDqyjL3/ch_1FEVHiGNRUDqyjL3acxVIi80/rcpt_FjzGftKMVmSyfkoQtlgNykaFCwakvny",
        "refunded": false,
        "refunds": {
          "object": "list",
          "data": [],
          "has_more": false,
          "total_count": 0,
          "url": "/v1/charges/ch_1FEVHiGNRUDqyjL3acxVIi80/refunds"
        },
        "review": null,
        "shipping": null,
        "source": {
          "id": "card_1FEVHfGNRUDqyjL3rwrdtE1E",
          "object": "card",
          "address_city": "Silver Spring",
          "address_country": "United States",
          "address_line1": "14238 Castle Blvd",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "MD",
          "address_zip": "20904",
          "address_zip_check": "pass",
          "brand": "Visa",
          "country": "US",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 2,
          "exp_year": 2032,
          "fingerprint": "xvoovnnTKuci9zAA",
          "funding": "credit",
          "last4": "4242",
          "metadata": {},
          "name": "ebrima Solomon jobe",
          "tokenization_method": null
        },
        "source_transfer": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "succeeded",
        "transfer_data": null,
        "transfer_group": null
      },
      {
        "id": "ch_1FF290GNRUDqyjL3e0B94dVc",
        "object": "charge",
        "amount": 3490,
        "amount_refunded": 0,
        "application": null,
        "application_fee": null,
        "application_fee_amount": null,
        "balance_transaction": "txn_1FF290GNRUDqyjL3ozhVJACM",
        "billing_details": {
          "address": {
            "city": "Los Angeles",
            "country": "United States",
            "line1": "1762 West blvd",
            "line2": null,
            "postal_code": "90019",
            "state": "CA"
          },
          "email": null,
          "name": "Ebrima Jobe",
          "phone": null
        },
        "captured": true,
        "created": 1567617586,
        "currency": "usd",
        "customer": null,
        "description": null,
        "destination": null,
        "dispute": null,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {},
        "invoice": null,
        "livemode": false,
        "metadata": {
          "eventId": "5d4f8597736a117fe680b83c",
          "updatedAt": "1567491275",
          "GA": "2",
          "RSVP": "0"
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "risk_level": "normal",
          "risk_score": 14,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "payment_intent": null,
        "payment_method": "card_1FF28wGNRUDqyjL3cLoudtHY",
        "payment_method_details": {
          "card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": "pass",
              "address_postal_code_check": "pass",
              "cvc_check": "pass"
            },
            "country": "US",
            "exp_month": 2,
            "exp_year": 2032,
            "fingerprint": "xvoovnnTKuci9zAA",
            "funding": "credit",
            "last4": "4242",
            "three_d_secure": null,
            "wallet": null
          },
          "type": "card"
        },
        "receipt_email": null,
        "receipt_number": null,
        "receipt_url": "https://pay.stripe.com/receipts/acct_1EWUgYGNRUDqyjL3/ch_1FF290GNRUDqyjL3e0B94dVc/rcpt_FkXDInsZFA4RWJePD42lkzbn6dz59GJ",
        "refunded": false,
        "refunds": {
          "object": "list",
          "data": [],
          "has_more": false,
          "total_count": 0,
          "url": "/v1/charges/ch_1FF290GNRUDqyjL3e0B94dVc/refunds"
        },
        "review": null,
        "shipping": null,
        "source": {
          "id": "card_1FF28wGNRUDqyjL3cLoudtHY",
          "object": "card",
          "address_city": "Los Angeles",
          "address_country": "United States",
          "address_line1": "1762 West blvd",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "CA",
          "address_zip": "90019",
          "address_zip_check": "pass",
          "brand": "Visa",
          "country": "US",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 2,
          "exp_year": 2032,
          "fingerprint": "xvoovnnTKuci9zAA",
          "funding": "credit",
          "last4": "4242",
          "metadata": {},
          "name": "Ebrima Jobe",
          "tokenization_method": null
        },
        "source_transfer": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "succeeded",
        "transfer_data": null,
        "transfer_group": null
      },
      {
        "id": "ch_1FF3p6GNRUDqyjL3ot2OCpAH",
        "object": "charge",
        "amount": 1745,
        "amount_refunded": 0,
        "application": null,
        "application_fee": null,
        "application_fee_amount": null,
        "balance_transaction": "txn_1FF3p6GNRUDqyjL3LOQedYVn",
        "billing_details": {
          "address": {
            "city": "Silver Spring",
            "country": "United States",
            "line1": "14238 Castle Blvd",
            "line2": null,
            "postal_code": "20904",
            "state": "MD"
          },
          "email": null,
          "name": "Ben Minah",
          "phone": null
        },
        "captured": true,
        "created": 1567624040,
        "currency": "usd",
        "customer": null,
        "description": null,
        "destination": null,
        "dispute": null,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {},
        "invoice": null,
        "livemode": false,
        "metadata": {
          "eventId": "5d4f8597736a117fe680b83c",
          "updatedAt": "1567617587",
          "GA": "1",
          "RSVP": "0"
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "risk_level": "normal",
          "risk_score": 34,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "payment_intent": null,
        "payment_method": "card_1FF3p3GNRUDqyjL3BzitsPa2",
        "payment_method_details": {
          "card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": "pass",
              "address_postal_code_check": "pass",
              "cvc_check": "pass"
            },
            "country": "US",
            "exp_month": 2,
            "exp_year": 2034,
            "fingerprint": "xvoovnnTKuci9zAA",
            "funding": "credit",
            "last4": "4242",
            "three_d_secure": null,
            "wallet": null
          },
          "type": "card"
        },
        "receipt_email": null,
        "receipt_number": null,
        "receipt_url": "https://pay.stripe.com/receipts/acct_1EWUgYGNRUDqyjL3/ch_1FF3p6GNRUDqyjL3ot2OCpAH/rcpt_FkYxfMarnc3SyKa8uOJi0Wbaq6TvXzF",
        "refunded": false,
        "refunds": {
          "object": "list",
          "data": [],
          "has_more": false,
          "total_count": 0,
          "url": "/v1/charges/ch_1FF3p6GNRUDqyjL3ot2OCpAH/refunds"
        },
        "review": null,
        "shipping": null,
        "source": {
          "id": "card_1FF3p3GNRUDqyjL3BzitsPa2",
          "object": "card",
          "address_city": "Silver Spring",
          "address_country": "United States",
          "address_line1": "14238 Castle Blvd",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "MD",
          "address_zip": "20904",
          "address_zip_check": "pass",
          "brand": "Visa",
          "country": "US",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 2,
          "exp_year": 2034,
          "fingerprint": "xvoovnnTKuci9zAA",
          "funding": "credit",
          "last4": "4242",
          "metadata": {},
          "name": "Ben Minah",
          "tokenization_method": null
        },
        "source_transfer": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "succeeded",
        "transfer_data": null,
        "transfer_group": null
      }
    ],
    "updatedAt": 1567650983
  }
  export default event